# 开发环境 - 不提交敏感信息

app:
  name: tenant-service
  env: dev

http:
  port: 8080

log:
  level: debug

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: tenant_db
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 25
  max_lifetime: 3600
